---
sudo_defaults:
  - "!requiretty"
  - "!visiblepw"
  - always_set_home
  - mail_badpass
  - env_reset
  - env_keep+=SSH_AUTH_SOCK
  - secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
sudo_sudoers:
  - name: "%sudo"
    nopasswd: true
sudo_sudoers_d: []
