---
- name: sudo | Install sudo (apt)
  apt: pkg=sudo state=present update_cache=yes
  when: ansible_pkg_mgr == 'apt'
  tags: sudo

- name: sudo | Install sudo (yum)
  yum: name=sudo state=present
  when: ansible_pkg_mgr == 'yum'
  tags: sudo

- name: sudo | Creating sudo group
  group: name=sudo state=present system=yes
  tags: sudo

- name: sudo | Creating sudoers.d directory
  file: path=/etc/sudoers.d owner=root group=root mode=0755 state=directory
  tags: sudo

- name: sudo | Creating sudoers files
  template: src=sudoers.j2 dest=/etc/sudoers owner=root group=root mode=0440 validate='/usr/sbin/visudo -cf %s'
  tags: sudo

- name: sudo | Create sudoers.d files
  template: src=sudoers.d.j2 dest="/etc/sudoers.d/{{ item.name }}" mode=0440 owner=root group=root validate="/usr/sbin/visudo -cf %s"
  with_items: "{{ sudo_sudoers_d }}"
  tags: sudo
