---
- name: Install programs
  hosts: all
  become: yes
  remote_user: root
  gather_facts: yes
  become_user: root
#  vars:
#    ansible_python_interpreter: /usr/bin/python3
  roles:
    - add-user-ansible
    - ansible-role-redis
    - ssh-deny-password

