---
- name: "flush sysctl"
  service: name=procps state=restarted

- name: "restart rsyslog"
  service: name=rsyslog state=restarted

- name: "disable haproxy"
  service: name=haproxy enabled=no state=stopped

- name: "start haproxy"
  service: name=haproxy state=started 
  register: start

- name: "reload haproxy"
  service: name=haproxy state=reloaded 

- name: "restart haproxy"
  service: name=haproxy state=restarted 
