---
- name: reload systemd
  command: systemctl daemon-reload

- name: restart nginx
  service: name=nginx state=restarted

- name: reload nginx
  service: name=nginx state=reloaded

- name: reload php5.6-fpm
  service: name=php5.6-fpm state=reloaded

- name: restart php5.6-fpm
  service: name=php5.6-fpm state=restarted

- name: reload haproxy
  service: name=haproxy state=reloaded
