---
- name: Install Prometheus
  hosts: all
  become: yes
  remote_user: root
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    # - nginx
    - installation-prometheus
    - install-grafana  
