---
dependencies: []

galaxy_info:
  role_name: redis
  author: Sergey Ignatov
  description: Redis for Linux
  company: "CB Sokolovsky"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Archlinux
      versions:
        - all
  galaxy_tags:
    - database
    - development
    - web
    - redis
    - cache
    - performance
