---
- name : Install Let's Encrypt Package
  apt:
    name: '{{ certbot_package }}'
    update_cache: yes
    state: latest

- name: Create and Install Cert Using {{ certbot_plugin }} Plugin
  command: "certbot certonly --'{{ certbot_plugin }}' -w '{{ webroot_path }}' -d '{{ domain_name }}' -m '{{ certbot_mail_address }}' --agree-tos --noninteractive --redirect"

- name: Copy config https nginx virtual_host
  # copy:
  template:
    src: devops.rebrain.srwx.net-https.j2
    dest: /etc/nginx/sites-available/{{ domain_name }}
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload nginx
    - check state

- name: Create simbolic link
  file:
    src: /etc/nginx/sites-available/{{ domain_name }}
    dest: /etc/nginx/sites-enabled/{{ domain_name }}
    owner: root
    group: root
    force: yes
    mode: 0644
    state: link
  notify:
    - reload nginx
    - check state

- name: Set Letsencrypt Cronjob for Certificate Auto Renewal
  cron:
    name: letsencrypt_renewal
    special_time: monthly
    job: "/usr/bin/certbot renew && reload nginx"
