---
- name: Download and install grafana
  shell: |
    apt-get install -y adduser libfontconfig1
    wget https://dl.grafana.com/oss/release/grafana_8.0.2_amd64.deb
    dpkg -i grafana_8.0.2_amd64.deb
    
- name: Enable services
  shell: |
    systemctl daemon-reload
    systemctl enable grafana-server.service
    systemctl start grafana-server.service
    
