---
- name: Install all for nginx
  block:
    - name: Add user
      user:
        name: Ansible
        groups: sudo
        shell: /bin/bash
        password: "{{ password }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa


    - name: Add SSH keys to remote hosts
      authorized_key:
        user: Ansible
        state: present
        key: "{{ lookup('file', '/home/sergey/.ssh/id_rsa.pub') }}"

    - name: Install packages
      apt:
        update_cache: yes
        pkg:
        - software-properties-common
        - python3
        - python3-pip
        - nginx

    - name: Install virtual host
      include_role:
        name: installation-virtual-host
  tags: nginx
