---
- name: packages | Installing https transport for apt
  apt: pkg=apt-transport-https state=present update_cache=yes
  tags: packages

- name: packages | Adding apt key for repository
  apt_key: url="{{ item.url }}" state=present
  with_items: "{{ packages_repositories_apt }}"
  when: item.url is defined
  tags: packages

- name: packages | Adding apt repository
  apt_repository: repo="{{ item.string }}" state=present
  with_items: "{{ packages_repositories_apt }}"
  tags: packages

- name: packages | Updating apt cache
  apt: update_cache="yes"
  tags: packages

- name: packages | Installing packages
  apt: pkg={{ item.name }} state={{ item.state | default("present") }}
  with_items: "{{ packages_list_apt }}"
  tags: packages
