---
- name: === Copy files ===
  copy:
    src: logstash-8.11.1-amd64.deb
    dest: /tmp/
    owner: root
    group: root
    mode: '0644'

- name: Install logstash
 shell: |
    cd /tmp
    dpkg -i logstash-8.11.1-amd64.deb

- name: Creat dir for certs
  shell: |
    cp -R /etc/elasticsearch/certs /etc/logstash
    chown -R root:logstash /etc/logstash/certs

- name: Copy config files
  copy:
    src: "{{ item }}"
    dest: /etc/logstash/conf.d/
    owner: root
    group: logstash
    mode: '0644'
  loop:
    - input.conf
    - output.conf
    - filter.conf

- name: Start or restart logstash service
  command: systemctl start logstash.service
  ignore_errors: true
  become: true

#- name: Check elastic
#  shell: systemctl status logstash.service
#  register: elasticsearch_service
  
