---
- name: === Copy files ===
  copy:
    src: filebeat-8.11.0-amd64.deb
    dest: /tmp/
    owner: root
    group: root
    mode: '0644'

- name: Install filebeat
  shell: |
    cd /tmp
    dpkg -i filebeat-8.11.0-amd64.deb

- name: Copy config file
  copy:
    src: filebeat.yml
    dest: /etc/filebeat/
    owner: root
    group: root 
    mode: '0644'

- name: Copy modules file
  copy:
    src: system.yml
    dest: /etc/filebeat/modules.d/
    owner: root
    group: root 
    mode: '0644'

- name: Start or restart filebeat service
  command: systemctl start filebeat.service
  ignore_errors: true
  become: true
  
# - name: Check filebeat
#   shell: systemctl status filebeat.service
#   register: filebeat_service
